# Expression Evaluation (User Defined Functions)

So far we have seen that ironArray has support for evaluating expressions that are passed as strings or as simple Python statements.  There is another, more flexible way for evaluating expressions called User Defined Functions, or UDFs for short.

UDFs are small functions that can be expressed in a simple subset of Python.  These functions are then passed to the internal LLVM compiler in ironArray and a binary specific and optimized for the local machine is generated.  This binary is optimized for the CPU and in addition, it will make use of the [Intel SVML library](https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/intrinsics/intrinsics-for-short-vector-math-library-operations/overview-intrinsics-for-short-vector-math-library-svml-functions.html) for accelerating the evaluation of transcendental functions.

Let's see how this works.

In [1]:
%load_ext memprofiler
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import iarray as ia

In [2]:
%%time
precip1 = ia.load("precip1.iarr")
precip2 = ia.load("precip2.iarr")
precip3 = ia.load("precip3.iarr")

CPU times: user 103 ms, sys: 203 ms, total: 306 ms
Wall time: 306 ms


Now, let's define a simple function that computes the mean for this data:

In [3]:
from iarray.udf import jit, Array, float32, float64

@jit()
def mean(out: Array(float32, 3),
         p1: Array(float32, 3),
         p2: Array(float32, 3),
         p3: Array(float32, 3)) -> int:

    l = out.shape[0]
    m = out.shape[1]
    n = out.shape[2]

    for i in range(l):
        for j in range(m):
            for k in range(n):
                value = p1[i,j,k] + p2[i,j,k] + p3[i,j,k]
                out[i,j,k] = value / 3

    return 0

This function is known as a _User Defined Function_ (_UDF_ for short) and it has a syntax that is a small subset of Python.  The order of the parameters passed matters: first comes the output and then a variable number of inputs (3 in this case).  The type of the parameters is always an `Array`, where you specify the data type (currently `float32` or `float64`), and the dimensions (3 in this case).

Finally, you can make use of the `shape` attribute of the parameters so as to access the _window_ to which the UDF will apply.  It is important to have in mind that the parameters do not have access to whole arrays passed to the function, but only to one part (also known as _window_).  Later we will see an example where we will work more explictly with windows.

Let's create the ironArray expression from this User Defined Function with:

In [4]:
%%time
precip_expr = ia.expr_from_udf(mean, [precip1, precip2, precip3], btune=False, favor=ia.Favors.BALANCE)

CPU times: user 22.8 ms, sys: 4.84 ms, total: 27.7 ms
Wall time: 27.3 ms


As can be seen, converting the user defined function into a native ironArray expression is pretty fast.  And as always, in order to do the actual evaluation, we have to call `.eval()` on the expression:

In [5]:
%%mprof_run iarray-mean
precip_mean = precip_expr.eval()
precip_mean

<IArray (720, 721, 1440) np.float32>

memprofiler: used 495.11 MiB RAM (peak of 495.11 MiB) in 0.7460 s, total RAM usage 1381.53 MiB


Let's compare this time with the evaluation via a regular lazy expression:

In [6]:
precip_expr2 = (precip1 + precip2 + precip3) / 3

In [7]:
%%mprof_run iarray-mean2
precip_mean2 = precip_expr2.eval()
precip_mean2

<IArray (720, 721, 1440) np.float32>

memprofiler: used 393.89 MiB RAM (peak of 395.06 MiB) in 0.7511 s, total RAM usage 1775.44 MiB


Ok, so the times and memory consumption are very close.  It turns out that UDFs compile and execute in ironArray make use the very same LLVM machinery, which explains times being similar.  It is up to you to decide to use one or the other depending on your needs.

An User Defined Function also have access to a good assortment of math functions, and you can access them via the usual Python `math` module. Let's see an example for our dataset, and although this does not make much sense for precipitation data, we can use this as an indication of the efficiency of the computational engine inside ironArray:

In [8]:
import math

@jit()
def trans(out: Array(float32, 3),
          p1: Array(float32, 3),
          p2: Array(float32, 3),
          p3: Array(float32, 3)) -> int:

    l = out.shape[0]
    m = out.shape[1]
    n = out.shape[2]

    for i in range(l):
        for j in range(m):
            for k in range(n):
                value = math.sin(p1[i,j,k]) * math.sin(p2[i,j,k]) + math.cos(p2[i,j,k])
                value *= math.tan(p1[i,j,k])
                value += math.sqrt(p3[i,j,k]) * 2
                out[i,j,k] = value

    return 0

In [9]:
%%time
precip_expr = ia.expr_from_udf(trans, [precip1, precip2, precip3])

CPU times: user 20 ms, sys: 4 ms, total: 24 ms
Wall time: 23.9 ms


In [10]:
%%mprof_run iarray-trans
precip_mean = precip_expr.eval()
precip_mean

<IArray (720, 721, 1440) np.float32>

memprofiler: used 651.00 MiB RAM (peak of 651.00 MiB) in 1.1034 s, total RAM usage 2427.06 MiB


In this case we see that the overhead of using transcendental functions is pretty the same than plain arithmetic operations (sum, rest, mult, division...).  This is a very significant fact because traditionally transcendental functions took really long time compared with plain arithmetic; not anymore thanks to the combination of LLVML and Intel SVML.  The good mix between compiler optimization (via LLVM) and SIMD usage (via SVML) makes this couple shine.

For the sake of comparison, let's compute the same expression with NumPy:

In [11]:
%%time
p1_ = precip1.data
p2_ = precip2.data
p3_ = precip3.data

CPU times: user 10.2 s, sys: 2 s, total: 12.2 s
Wall time: 4.4 s


In [12]:
%%mprof_run np_trans
np_result = (np.tan(p1_) * (np.sin(p1_) * np.sin(p2_) + np.cos(p2_)) + np.sqrt(p3_) * 2)

memprofiler: used 2852.01 MiB RAM (peak of 8555.00 MiB) in 8.3983 s, total RAM usage 13849.50 MiB


This is really slow, but this is kind of expected because NumPy does not have support for SVML or multithreading (at this time at least), and we all know that transcendental functions always took quite a lot to execute on a regular CPU.

## Working with data windows

We already mentioned that User Defined Functions can access only a part (a window) of the dataset.  Here we will have a more in deep look at how this works and how to squeeze all the functionality out of it.

Let's start by creating an zeroed array, and let's populate it with a UDF so that we get a diagonal array:

In [13]:
e = ia.zeros((10, 10), dtype=np.float64)

The UDF looks like:

In [14]:
@jit
def fill_diag(out: Array(float64, 2), in1: Array(float64, 2)) -> int:
    n = out.shape[0]
    m = out.shape[1]
    for i in range(n):
        for j in range(m):
            out[i, j] = 1. if i == j else in1[i, j]

    return 0

In [15]:
fill_expr = ia.expr_from_udf(fill_diag, [e], chunks=(5, 5), blocks=(3, 3))
result = fill_expr.eval()

In [16]:
print(result.data)

[[1. 0. 0. 1. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 1. 0. 0. 1.]]


So, instead of getting a diagonal array, we get a lot of non-zeros outside of the diagonal.  What we are seeing here is some internal details of how expressions are evaluated inside ironArray.  The evaluation engine splits the inputs in blocks (also called **data windows** in this context), so that the engine can evaluate them in parallel.  So `out.shape` in the UDF above refers to just this data window.

In fact, if you look at the pattern above, you can see small 3x3 arrays (the size of blocks, or data windows) that are diagonal.  Incidentally, we don't see a patchwork made of full 3x3 arrays because the chunks are 5x5, so the data windows also end when a chunk ends.  Take some time to recognize the patterns because this will allow you to get a nice picture of how data is arranged during evaluations.

Now, let's go back to our original goal of getting a diagonal array.  Have a look at this new UDF:

In [17]:
@jit
def fill_diag2(out: Array(float64, 2), in1: Array(float64, 2)) -> int:
    n = out.shape[0]
    m = out.shape[1]
    start_n = out.window_start[0]
    start_m = out.window_start[1]
    for i in range(n):
        for j in range(m):
            out[i, j] = 1. if i == j and start_n == start_m else in1[i, j]
            # another way
            # out[i, j] = 1. if i + start_n == j + start_m else in1[i, j]

    return 0

In [18]:
fill_expr2 = ia.expr_from_udf(fill_diag2, [e], chunks=(5, 5), blocks=(3, 3))
result = fill_expr2.eval()

In [19]:
print(result.data)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Ok, that's much better.  Let's recap what the UDF is doing now.  First, it is getting the starting points for each data window via the `out.window_start` property.  Second, we are enforcing that we want to add ones only in the data windows that lay the diagonal, and not outside.

In general, you should keep in mind that you can access any element in operands (or result) arrays as long as it is inside the current data window (the block).  Although initially this might be a bit confusing, this 'feature' enables performing expressions in parallel (i.e. one thread evaluates its corresponding window).  Combine this with SVML/LLVM and you will get the principles on why ironArray can be so fast in evaluating UDFs.